Console.Write("Cidades ");
Thread.Sleep(500);
Console.Write(" Do ");
Thread.Sleep(500);
Console.Write("Litoral ");
Thread.Sleep(500);
Console.Write("Sul ");
Thread.Sleep(500);
Console.Write("De ");
Thread.Sleep(500);
Console.Write("São ");
Thread.Sleep(500);
Console.Write("Paulo");
Thread.Sleep(900);
Console.WriteLine("");
Console.WriteLine("1");
Thread.Sleep(600);
Console.Write(" ");
Thread.Sleep(500);
Console.Write("S");
Thread.Sleep(500);
Console.Write("Ã");
Thread.Sleep(500);
Console.Write("O");
Thread.Sleep(500);
Console.Write(" ");
Thread.Sleep(500);
Console.Write("V");
Thread.Sleep(500);
Console.Write("I");
Thread.Sleep(500);
Console.Write("C");
Thread.Sleep(500);
Console.Write("E");
Thread.Sleep(500);  
Console.Write("N");
Thread.Sleep(500);
Console.Write("T");
Thread.Sleep(500);
Console.Write("E");
Thread.Sleep(500);
Console.WriteLine("");
Console.WriteLine("2");
Thread.Sleep(600);
Console.Write(" ");
Thread.Sleep(500);
Console.Write("P");
Thread.Sleep(500);
Console.Write("R");
Thread.Sleep(500);
Console.Write("A");
Thread.Sleep(500);
Console.Write("I");
Thread.Sleep(500);
Console.Write("A");
Thread.Sleep(500);
Console.Write(" ");
Thread.Sleep(500);
Console.Write("G");
Thread.Sleep(500);
Console.Write("R");
Thread.Sleep(500);
Console.Write("A");
Thread.Sleep(500);
Console.Write("N");
Thread.Sleep(500);
Console.Write("D");
Thread.Sleep(500);
Console.Write("E");
Thread.Sleep(900);
Console.WriteLine("");
Console.WriteLine("3");
Thread.Sleep(500);
Console.Write("M");
Thread.Sleep(500);
Console.Write("O");
Thread.Sleep(500);
Console.Write("N");
Thread.Sleep(500);
Console.Write("G");
Thread.Sleep(500);
Console.Write("A");
Thread.Sleep(500);
Console.Write("G");
Thread.Sleep(500);
Console.Write("U");
Thread.Sleep(500);
Console.Write("A");